# Config file for sample.py project
title = 'Sample Project'
sessionId = "20180310T123000"
subjectName = "0301181_sample"
subjectNum = 1
subjectDay = 1
sessionNum = 1
Runs = [1, 2, 3]
ScanNums = [11, 13, 15]
plotTitle = 'Realtime Plot'
plotXLabel = 'Sample #'
plotYLabel = 'Value'
plotXRangeLow = 0
plotXRangeHigh = 20
plotYRangeLow = -1
plotYRangeHigh = 1
